### ISSUE TITLE
error when trying to run the game

### ISSUE THREAD

**Issue by Maxaxa** [FrostAndWinter/OriginalAdventure#14]
I tried to run the game with command and in IDE. In both cases i get following error after choosing Start Singleplayer, could there be something buggy? Or maybe i'm forgetting something:

Microsoft Windows [Version 10.0.10240](c) 2015 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\Maxaxa\Downloads\OriginalAdventure-master>gradlew runPretty run
:runPretty
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:run
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
        at swen.adventure.game.AdventureGame.startGame(AdventureGame.java:448)
        at swen.adventure.game.LauncherGUI.startGame(LauncherGUI.java:146)
        at swen.adventure.game.LauncherGUI.lambda$new$162(LauncherGUI.java:84)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:20
22)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.jav
a:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel
.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259
)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonL
istener.java:252)
        at java.awt.Component.processMouseEvent(Component.java:6535)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6300)
        at java.awt.Container.processEvent(Container.java:2236)
        at java.awt.Component.dispatchEventImpl(Component.java:4891)
        at java.awt.Container.dispatchEventImpl(Container.java:2294)
        at java.awt.Component.dispatchEvent(Component.java:4713)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888
)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)

```
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
```

rivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(Eventava:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThre
ad.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.
java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThre
ad.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)

```
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Caused by: java.util.regex.PatternSyntaxException: Illegal/unsupported escape se
quence near index 8
classes\main
        ^
        at java.util.regex.Pattern.error(Pattern.java:1955)
        at java.util.regex.Pattern.escape(Pattern.java:2471)
        at java.util.regex.Pattern.atom(Pattern.java:2198)
        at java.util.regex.Pattern.sequence(Pattern.java:2130)
        at java.util.regex.Pattern.expr(Pattern.java:1996)
        at java.util.regex.Pattern.compile(Pattern.java:1696)
        at java.util.regex.Pattern.<init>(Pattern.java:1351)
        at java.util.regex.Pattern.compile(Pattern.java:1028)
        at java.lang.String.replaceFirst(String.java:2178)
        at swen.adventure.engine.Utilities.<clinit>(Utilities.java:40)
        ... 39 more

> Building 80% > :run

**Comment by danielbraithwt** [comment]
Could you try it with runUgly instead of runPretty? see if that helps

**Comment by troughton** [comment]
Hi Maxaxa,

I'm not quite sure how you found this project; I'm guessing from the "Alle Rechte vorbehalten" and the time you posted that you're not associated with ECS at Victoria, although I might be completely incorrect in that. For context, this is a University project that we did as a group, and as far as I'm aware we've never tested it on Windows.

With that said, if you really do want to run it, then the problem is in the Utilities.java file in the swen.adventure.engine package. Find that file, and replace the line:

`BasePath = new File(path).getPath().replaceFirst("classes" + File.separator + "main", "resources" + File.separator + "main");`

with

`BasePath = new File(path).getPath().replaceFirst("classes", "resources");`

What seems to be the issue is that the Regex parser is reading the Windows path separator (\) as an escape sequence; on OS X and Linux/Unix, the separator is /, so no issue occurs.

We won't be pushing a fix to this at this stage, since we may need to keep the repository locked in its current state for a while.

**Comment by Maxaxa** [comment]
Yes, you're right. I just stumbled over your project and found it interesting. I thought something like that would be the issue thanks.
